version: '3.8'
services:

  server:
    build: ./server
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - logs:/project/logs
      - ./server:/project
      - /project/node_modules
    networks:
      sern:
        ipv4_address: 172.24.0.4
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/project/src
    stdin_open: true
    networks:
      sern:
        ipv4_address: 172.24.0.3

  mysql:
    build: ./mysql
    volumes:
      - data:/data/db
    environment:
      DB_HOST: root
      DB_USER: root
      MYSQL_ROOT_PASSWORD: root
      DB_NAME: inzynierka
    ports:
      - "3306:3306"
    networks:
      sern:
        ipv4_address: 172.24.0.2
    restart: always

networks:
  sern:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.1/16

volumes:
  data:
  logs: