require('dotenv').config()
const express = require('express')
const app = express()
const cors = require('cors')
const { sequelize } = require("./db")
const db = require("./db")
const userRoutes = require("./routes/users")
const authRoutes = require("./routes/auth")
const dietsRoutes = require("./routes/diets")
const dishesRoutes = require("./routes/dishes")
const ingredientsRoutes = require("./routes/ingredients")
const macronutrientsRoutes = require("./routes/macronutrients")
const recipesRoutes = require("./routes/recipes")
const dishes_historiesRoutes = require("./routes/dishes_histories")
const diet_has_dishesRoutes = require("./routes/diet_has_dishes")

app.use(express.json())
app.use(cors())

const port = process.env.PORT
app.listen(port, () => console.log(`Nasłuchiwanie na porcie ${port}`))

app.use("/api/users", userRoutes)
app.use("/api/auth", authRoutes)
app.use("/api/diets", dietsRoutes)
app.use("/api/dishes", dishesRoutes)
app.use("/api/ingredients", ingredientsRoutes)
app.use("/api/macronutrients", macronutrientsRoutes)
app.use("/api/recipes", recipesRoutes)
app.use("/api/dishes_histories", dishes_historiesRoutes)
app.use("/api/diet_has_dishes", diet_has_dishesRoutes)