insert into Diet_has_dishes(diet_id, dish_id) values(1, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(1, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(2, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(2, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(3, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(3, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(4, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(4, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(5, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(5, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(6, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(6, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(7, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(7, 9);

insert into Diet_has_dishes(diet_id, dish_id) values(8, 1);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 2);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 3);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 4);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 5);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 6);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 7);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 8);
insert into Diet_has_dishes(diet_id, dish_id) values(8, 9);